### ISSUE TITLE
Broken link to penn state article at the bottom of the page

### ISSUE THREAD

**Issue by halemade** [learn-co-curriculum/dsc-arma-models#1]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

> https://learning.flatironschool.com/courses/3510/pages/arma-models?module_item_id=288314

## Describe the bug

> broken link

## What is the expected behavior?

> Write a clear and concise description of what you expected to happen.

## Screenshots

> If applicable, attach scree
![Screen Shot 2021-08-27 at 9 56 53 AM](https://user-images.githubusercontent.com/70820976/131138918-17407f37-14e8-4ade-a548-129925015ec4.png)
nshots to help explain your problem.

## What OS are you using?

- [ X] OS X
- [ ] WSL
- [ ] Linux

## Any additional context?

> Add any other context about the problem here.

**Comment by hoffm386** [comment]
Thank you for flagging! The updated link is https://online.stat.psu.edu/stat510/ and this has been included in the latest edits https://github.com/learn-co-curriculum/dsc-arma-models/commit/5f8b61b76eba1b0783f28b18c6961c6cd760e157
